version: '3.8'

services:
  db:
    image: postgres:16.0-alpine
    volumes:
      - psql_db:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  
  # front:
  #   build: ./front/front-lenta/
  #   volumes:
  #     - ./front/front-lenta/:/app/result_build/
  #   depends_on:
  #     - db

  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env.prod
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/
      - static_value:/var/html/static
      - media_value:/var/html/media
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  psql_db: