URL_FOR_READY: 'http://host.docker.internal'

PATH_SALES_DF_TRAIN: '/raw/sales_df_train.csv'
PATH_PR_DF: '/raw/pr_df.csv'
PATH_ST_DF: '/raw/st_df.csv'
PATH_TO_SUMISSION_DF: '/raw/sales_submission.csv'
PATH_TO_HOLIDAYS: '/holidays.csv'
PATH_TO_MODELS: '/models/model.pkl'