name: Vanga app workflow

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [devlop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r ./backend/backend_foodgram/requirements.txt

      - name: Test with flake8 and django tests
        run: |
          python -m flake8